"""The policy file and its environment overrides, which is how the container is steered."""

from __future__ import annotations

import json
import os
import unittest

from bonehub_quality_check_server.config import (
    ENV_PREFIX,
    QCServerConfig,
    resolve_dataset_root,
    resolve_state_dir,
)

from tests.support import QCTestCase, clear_qc_env


class ConfigDefaultsTests(unittest.TestCase):
    def setUp(self) -> None:
        clear_qc_env()
        self.addCleanup(clear_qc_env)

    def test_defaults_match_the_intended_policy(self):
        config = QCServerConfig()
        # Subjects generated by BoneHub but not yet checked are what needs reviewing.
        self.assertEqual(config.eligible_label_values, [2])
        # A confirmed label becomes 3: "passed quality check".
        self.assertEqual(config.confirmed_label_value, 3)
        self.assertFalse(config.include_subjects_without_segmentation)
        self.assertFalse(config.requeue_rejected)
        self.assertIsNone(config.allowed_dataset_ids)
        self.assertEqual(config.assignment_strategy, "sequential")
        self.assertEqual(config.max_concurrent_assignments_per_user, 1)

    def test_rejects_a_label_value_the_schema_does_not_define(self):
        with self.assertRaises(ValueError):
            QCServerConfig(eligible_label_values=[7])
        with self.assertRaises(ValueError):
            QCServerConfig(confirmed_label_value=9)

    def test_rejects_an_empty_eligible_list(self):
        with self.assertRaises(ValueError):
            QCServerConfig(eligible_label_values=[])

    def test_eligible_values_are_de_duplicated_and_sorted(self):
        self.assertEqual(QCServerConfig(eligible_label_values=[2, 1, 2]).eligible_label_values, [1, 2])

    def test_rejects_unknown_fields(self):
        with self.assertRaises(ValueError):
            QCServerConfig(not_a_real_field=1)

    def test_lease_ttl_has_a_floor(self):
        with self.assertRaises(ValueError):
            QCServerConfig(lease_ttl_seconds=5)


class ConfigPersistenceTests(QCTestCase):
    def test_save_then_load_round_trips(self):
        path = self.tmp_path / "config.json"
        original = QCServerConfig(
            eligible_label_values=[1, 2],
            allowed_dataset_ids=[3, 7],
            assignment_strategy="random",
            requeue_rejected=True,
        )
        original.save(path)
        self.assertEqual(QCServerConfig.load(path).model_dump(), original.model_dump())

    def test_load_of_a_missing_file_gives_defaults(self):
        config = QCServerConfig.load(self.tmp_path / "nope.json")
        self.assertEqual(config.model_dump(), QCServerConfig().model_dump())

    def test_save_is_atomic_and_leaves_no_temporary_file(self):
        path = self.tmp_path / "state" / "config.json"
        QCServerConfig().save(path)
        self.assertTrue(path.exists())
        self.assertFalse(path.with_name(path.name + ".tmp").exists())
        json.loads(path.read_text(encoding="utf-8"))


class ConfigEnvironmentOverrideTests(QCTestCase):
    """``BONEHUB_QC_*`` wins over the stored file, which is how docker-compose configures."""

    def test_int_bool_and_list_overrides_are_parsed(self):
        path = self.tmp_path / "config.json"
        QCServerConfig().save(path)

        os.environ[f"{ENV_PREFIX}LEASE_TTL_SECONDS"] = "600"
        os.environ[f"{ENV_PREFIX}REQUEUE_REJECTED"] = "true"
        os.environ[f"{ENV_PREFIX}ALLOWED_DATASET_IDS"] = "1, 4, 9"
        os.environ[f"{ENV_PREFIX}ASSIGNMENT_STRATEGY"] = "random"

        config = QCServerConfig.load(path)
        self.assertEqual(config.lease_ttl_seconds, 600)
        self.assertTrue(config.requeue_rejected)
        self.assertEqual(config.allowed_dataset_ids, [1, 4, 9])
        self.assertEqual(config.assignment_strategy, "random")

    def test_allowed_dataset_ids_can_be_cleared_back_to_every_dataset(self):
        path = self.tmp_path / "config.json"
        QCServerConfig(allowed_dataset_ids=[1]).save(path)
        os.environ[f"{ENV_PREFIX}ALLOWED_DATASET_IDS"] = "none"
        self.assertIsNone(QCServerConfig.load(path).allowed_dataset_ids)

    def test_an_empty_variable_is_ignored_rather_than_parsed(self):
        path = self.tmp_path / "config.json"
        QCServerConfig(lease_ttl_seconds=999).save(path)
        os.environ[f"{ENV_PREFIX}LEASE_TTL_SECONDS"] = ""
        self.assertEqual(QCServerConfig.load(path).lease_ttl_seconds, 999)

    def test_falsey_words_all_turn_a_flag_off(self):
        path = self.tmp_path / "config.json"
        QCServerConfig(requeue_rejected=True).save(path)
        for word in ["false", "0", "no", "off"]:
            os.environ[f"{ENV_PREFIX}REQUEUE_REJECTED"] = word
            self.assertFalse(QCServerConfig.load(path).requeue_rejected, word)


class PathResolutionTests(QCTestCase):
    def test_dataset_root_comes_from_the_environment(self):
        os.environ[f"{ENV_PREFIX}DATASET_ROOT"] = str(self.dataset_root)
        self.assertEqual(resolve_dataset_root(), self.dataset_root)

    def test_a_missing_dataset_root_is_a_clear_startup_error(self):
        with self.assertRaises(RuntimeError) as ctx:
            resolve_dataset_root()
        self.assertIn("DATASET_ROOT", str(ctx.exception))

    def test_state_dir_defaults_to_a_hidden_folder_inside_the_dataset(self):
        self.assertEqual(resolve_state_dir(self.dataset_root), self.dataset_root / ".bonehub_qc")

    def test_state_dir_name_is_overridable(self):
        os.environ[f"{ENV_PREFIX}STATE_DIR_NAME"] = "_qc"
        self.assertEqual(resolve_state_dir(self.dataset_root), self.dataset_root / "_qc")


if __name__ == "__main__":
    unittest.main()
