"""Server configuration.

The configuration lives in ``<dataset_root>/<state_dir_name>/config.json`` so that a
dataset folder carries its own quality-check policy around with it. Any field can be
overridden at startup through an environment variable named ``BONEHUB_QC_<FIELD>``,
which is how the Docker image is configured.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator

from bonehub_data_schema.subject_info import VALID_LABEL_VALUES

ENV_PREFIX = "BONEHUB_QC_"
DEFAULT_STATE_DIR_NAME = ".bonehub_qc"
CONFIG_FILE_NAME = "config.json"


class QCServerConfig(BaseModel):
    """Policy that decides which subjects are handed out and what a submission does."""

    # --- queue policy -------------------------------------------------------
    eligible_label_values: list[int] = Field(
        default_factory=lambda: [2],
        description=(
            "A subject is queued for quality check when at least one of its segmentation "
            "labels holds one of these values. Defaults to [2] = 'available, automatically "
            "generated by BoneHub, without quality check'."
        ),
    )
    include_subjects_without_segmentation: bool = Field(
        False,
        description="Also queue subjects that have an image but no segmentation at all, so reviewers can create one.",
    )
    requeue_rejected: bool = Field(
        False,
        description="Hand a subject out again after a reviewer submitted it with quality_check_confirmed=false.",
    )
    allowed_dataset_ids: list[int] | None = Field(
        None,
        description="Restrict the whole server to these dataset ids. None means every dataset under the root.",
    )

    # --- assignment policy --------------------------------------------------
    assignment_strategy: Literal["sequential", "random"] = Field(
        "sequential",
        description="'sequential' hands out the lowest free subject, 'random' picks a free subject at random.",
    )
    lease_ttl_seconds: int = Field(
        24 * 3600,
        ge=60,
        description="How long a reviewer keeps a subject before it returns to the queue.",
    )
    max_concurrent_assignments_per_user: int = Field(
        1,
        ge=1,
        description="How many subjects a single reviewer may hold at the same time.",
    )
    index_refresh_seconds: int = Field(
        300,
        ge=0,
        description="How often the subject index is rebuilt from disk. 0 rebuilds on every request.",
    )

    # --- submission policy --------------------------------------------------
    confirmed_label_value: int = Field(
        3,
        description="Value written into Subject_info for labels a reviewer confirmed.",
    )
    mark_removed_labels_absent: bool = Field(
        True,
        description=(
            "When a confirmed submission no longer contains a label that used to be in the "
            "segmentation, set that label to 0 ('not available, confirmed') instead of leaving it."
        ),
    )
    require_geometry_match: bool = Field(
        True,
        description="Reject a submitted segmentation whose voxel grid does not match the subject's image.",
    )
    keep_segmentation_backups: bool = Field(
        True,
        description="Copy the previous segmentation into the state folder before overwriting it.",
    )
    max_upload_bytes: int = Field(
        512 * 1024 * 1024,
        ge=1,
        description="Largest segmentation upload accepted from a client.",
    )

    model_config = ConfigDict(extra="forbid", validate_assignment=True)

    @field_validator("eligible_label_values")
    @classmethod
    def check_eligible_label_values(cls, values: list[int]) -> list[int]:
        if not values:
            raise ValueError("eligible_label_values must not be empty.")
        for value in values:
            if value not in VALID_LABEL_VALUES:
                raise ValueError(f"Invalid label value {value}. Valid values are {sorted(VALID_LABEL_VALUES)}.")
        return sorted(set(values))

    @field_validator("confirmed_label_value")
    @classmethod
    def check_confirmed_label_value(cls, value: int) -> int:
        if value not in VALID_LABEL_VALUES:
            raise ValueError(f"Invalid label value {value}. Valid values are {sorted(VALID_LABEL_VALUES)}.")
        return value

    # --- persistence --------------------------------------------------------
    @classmethod
    def load(cls, config_path: Path) -> "QCServerConfig":
        """Read the config file if it exists, then apply ``BONEHUB_QC_*`` overrides."""
        data: dict = {}
        if config_path.exists():
            with open(config_path, "r", encoding="utf-8") as f:
                data = json.load(f)
        data.update(cls._env_overrides())
        return cls(**data)

    def save(self, config_path: Path) -> None:
        config_path.parent.mkdir(parents=True, exist_ok=True)
        tmp_path = config_path.with_name(config_path.name + ".tmp")
        with open(tmp_path, "w", encoding="utf-8") as f:
            json.dump(self.model_dump(), f, indent=4)
        os.replace(tmp_path, config_path)

    @classmethod
    def _env_overrides(cls) -> dict:
        """Collect ``BONEHUB_QC_<FIELD>`` variables that match a config field."""
        overrides: dict = {}
        for name, field in cls.model_fields.items():
            raw = os.environ.get(f"{ENV_PREFIX}{name.upper()}")
            if raw is None or raw == "":
                continue
            overrides[name] = _parse_env_value(raw, field.annotation)
        return overrides


def _parse_env_value(raw: str, annotation) -> object:
    """Turn an environment string into the type the config field expects."""
    text = raw.strip()
    annotation_text = str(annotation)
    if "bool" in annotation_text:
        return text.lower() in {"1", "true", "yes", "on"}
    if "list" in annotation_text:
        if text.lower() in {"none", "null"}:
            return None
        items = [item.strip() for item in text.split(",") if item.strip()]
        return [int(item) for item in items] if "int" in annotation_text else items
    if "int" in annotation_text:
        return int(text)
    return text


def resolve_dataset_root() -> Path:
    """Dataset root the server operates on, from ``BONEHUB_QC_DATASET_ROOT``."""
    raw = os.environ.get(f"{ENV_PREFIX}DATASET_ROOT")
    if not raw:
        raise RuntimeError(
            f"{ENV_PREFIX}DATASET_ROOT is not set. Point it at a folder in BoneHub data structure format."
        )
    return Path(raw)


def resolve_state_dir(dataset_root: Path) -> Path:
    """Folder inside the dataset root where users, assignments, logs and backups live."""
    name = os.environ.get(f"{ENV_PREFIX}STATE_DIR_NAME", DEFAULT_STATE_DIR_NAME)
    return dataset_root / name
